language: php
php:
  - 5.6
  - hhvm
  - nightly
  - 7

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  slack: talk-point:KKWcziADw3uRP3jOmUasdG14
